---
name: Tests
on:
  workflow_call:
    secrets:
      CODACY_PROJECT_TOKEN:
        description: "The key to record the execution to Codacy"
        required: true
      CODECOV_TOKEN:
        description: "The key to record the code coverage to CodeCov"
        required: true
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
        with:
          cache: pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --cov --cov-report=xml

      - name: Upload coverage to Codecov
        # v5
        uses: codecov/codecov-action@1fecca8ce3a22284e70b371077fb5219f54095b8
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella

      - name: Upload coverage to Codacy
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
