---
name: Release Automation
on:
  workflow_call:
    inputs:
      PLUGIN_LIST:
        description: "List of plugins to use with the release automation"
        required: true
        type: string
    secrets:
      PROJECT_GITHUB_TOKEN:
        description: "Access token for GitHub"
        required: true

jobs:
  configuration:
    name: Configuration for Release Automation
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.configuration.outputs.branch }}
    steps:
      - id: configuration
        name: Release options
        run: |
          branch=${GITHUB_REF##*/}

          echo "branch=$branch" >> "$GITHUB_OUTPUT"

  release-automation:
    name: Release Automation
    runs-on: ubuntu-latest
    needs: configuration
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          ref: ${{ needs.configuration.outputs.branch }}

      - name: Running release automation
        uses: juancarlosjr97/release-it-containerized@c971f4e8703811ce620bdef88fd4e9dbd1e06b58 # 0.7.48
        with:
          github_token: ${{ secrets.PROJECT_GITHUB_TOKEN }}
          plugins_list: ${{ inputs.PLUGIN_LIST }}
