---
name: Tests
on:
  workflow_call:
    secrets:
      CODACY_PROJECT_TOKEN:
        description: "The key to record the execution to Codacy"
        required: true
      CODECOV_TOKEN:
        description: "The key to record the code coverage to CodeCov"
        required: true
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          cache: pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --cov --cov-report=xml

      - name: Upload coverage to Codecov
        # v5
        uses: codecov/codecov-action@3cb13a12348ef4ffcf9783ac0f74954f92113e33
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella

      - name: Upload coverage to Codacy
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
