---
name: Tests
on:
  workflow_call:
    secrets:
      CODACY_PROJECT_TOKEN:
        description: "The key to record the execution to Codacy"
        required: true
      CODECOV_TOKEN:
        description: "The key to record the code coverage to CodeCov"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --cov --cov-report=xml

      - name: Upload coverage to Codecov
        # v5
        uses: codecov/codecov-action@7f8b4b4bde536c465e797be725718b88c5d95e0e
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella

      - name: Upload coverage reports to Codacy
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
